baseurl = "http://muay-thai-meditationen.net/"
languageCode = 'de-de'
DefaultContentLanguage = "de"
title = "Muay Thai Blog"
# Using theme as git submodule 
theme = "beautifulhugo"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"

[languages]
  [languages.en] 
    contentDir = "content/en"
  [languages.de]
    contentDir = "content/de"
  [languages.de.menu]
    [[languages.de.menu.main]]
      name = "Blog"
      url = ""
    [[languages.de.menu.main]]
      name = "Über"
      url = "page/about"
    [[languages.de.menu.main]]
      name = "Kontakt"
      url = "page/contact"

  [languages.en.menu]
    [[languages.en.menu.main]]
      name = "Blog"
      url = ""
      weight = 1
    [[languages.en.menu.main]]
      name = "About"
      url = "page/about"
    [[languages.en.menu.main]]
      name = "Contact"
      url = "page/contact"

[Services]
  [Services.Disqus]
    # Shortname = "XXX"
  [Services.googleAnalytics]
    # id = "XXX"

[Params]
  selfHosted = true
  homeTitle = "Muay Thai Blog"
  subtitle = "Meditationen"
  mainSections = ["post","posts"]
#  logo = "img/avatar-icon.png" # Expecting square dimensions
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  readingTime = true
  wordCount = true
  useHLJS = true
  socialShare = false
  delayDisqus = true
  showRelatedPosts = true
#  cusdisID = "XXX" # Get your App id from cusdis.com
#  hideAuthor = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"
#  disclaimerText = "The opinions expressed herein are my own personal opinions and do not represent my employer’s view in any way."

[[Params.bigimg]]
  src = "img/bg-index.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Params.author]
  # Set only your "username" for default hosts and full URLs otherwise (e.g., "https://MyGitLab.org/username")
  name = "V"
  email = "v.networks@posteo.de"
  instagram = "v__glb"
  github = "v-glb"